import './global.scss';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { ReactNode } from 'react';
import cn from 'classnames';
import {CookieBanner} from '@supernaut/features';
import {GoogleAnalytics} from '@supernaut/utils';

export const metadata = {
  title: 'Welcome to Supernaut',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      className={cn(`${GeistSans.variable} ${GeistMono.variable}`, 'dark')}
    >

      <GoogleAnalytics GA_MEASUREMENT_ID={process.env.NEXT_GOOGLE_ANALYTICS_ID || ''}/>
      <body>{children}
      <CookieBanner />
      </body>
    </html>
  );
}
