[build]
command = "npm run build"
publish = ".next"


[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = '''
            max-age=63072000;
            includeSubDomains;
            preload'''
[[headers]]
for = "/images/*"
[headers.values]
cache-control = "public, max-age=31536000, immutable"
[[headers]]
for = "/images/uploads/*"
[headers.values]
cache-control = "public, max-age=31536000, immutable"
[[headers]]
for = "*.jpg"
[headers.values]
cache-control = "public, max-age=31536000, immutable"
[[headers]]
for = "*.css"
[headers.values]
cache-control = "public, max-age=31536000, immutable"
[[headers]]
for = "*.js"
[headers.values]
cache-control = "public, max-age=31536000, immutable"
[[headers]]
for = "*.html"
[headers.values]
cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''


[[plugins]]
package = "netlify-plugin-cypress"
[plugins.inputs]
record = true
group = "Testing Built Site"
